-- MySQL Script generated by MySQL Workbench
-- mar. 13 nov. 2018 11:19:52 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema oquizz
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `author` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `updated_at_UNIQUE` (`updated_at` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `level`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `level` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `updated_at_UNIQUE` (`updated_at` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quizz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizz` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  `author_id` INT UNSIGNED NOT NULL,
  `level_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_quizz_author1_idx` (`author_id` ASC),
  INDEX `fk_quizz_level1_idx` (`level_id` ASC),
  UNIQUE INDEX `updated_at_UNIQUE` (`updated_at` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `response`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `response` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `response_1` VARCHAR(255) NOT NULL,
  `response_2` VARCHAR(255) NOT NULL,
  `response_3` VARCHAR(255) NOT NULL,
  `response_4` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `updated_at_UNIQUE` (`updated_at` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `question` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  `response_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_question_response1_idx` (`response_id` ASC),
  UNIQUE INDEX `updated_at_UNIQUE` (`updated_at` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `theme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `theme` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `updated_at_UNIQUE` (`updated_at` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `subject` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `updated_at_UNIQUE` (`updated_at` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `information`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `information` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `updated_at_UNIQUE` (`updated_at` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quizz_has_theme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizz_has_theme` (
  `quizz_id` INT UNSIGNED NOT NULL,
  `theme_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`quizz_id`, `theme_id`),
  INDEX `fk_quizz_has_theme_theme1_idx` (`theme_id` ASC),
  INDEX `fk_quizz_has_theme_quizz_idx` (`quizz_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quizz_has_subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizz_has_subject` (
  `quizz_id` INT UNSIGNED NOT NULL,
  `subject_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`quizz_id`, `subject_id`),
  INDEX `fk_quizz_has_subject_subject1_idx` (`subject_id` ASC),
  INDEX `fk_quizz_has_subject_quizz1_idx` (`quizz_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quizz_has_information`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizz_has_information` (
  `quizz_id` INT UNSIGNED NOT NULL,
  `information_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`quizz_id`, `information_id`),
  INDEX `fk_quizz_has_information_information1_idx` (`information_id` ASC),
  INDEX `fk_quizz_has_information_quizz1_idx` (`quizz_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quizz_has_question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizz_has_question` (
  `quizz_id` INT UNSIGNED NOT NULL,
  `question_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`quizz_id`, `question_id`),
  INDEX `fk_quizz_has_question_question1_idx` (`question_id` ASC),
  INDEX `fk_quizz_has_question_quizz1_idx` (`quizz_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
